version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.license.self_generated.type=trial
      - xpack.encryptedSavedObjects.encryptionKey=thisMustBeExactly32CharactersLon
      - xpack.reporting.encryptionKey=thisMustBeExactly32CharactersLon
      - xpack.actions.encryptionKey=thisMustBeExactly32CharactersLon
      - xpack.alerting.encryptionKey=thisMustBeExactly32CharactersLon
      - xpack.task_manager.encryptionKey=thisMustBeExactly32CharactersLon
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.0
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - NODE_OPTIONS=--openssl-legacy-provider
      - xpack.encryptedSavedObjects.encryptionKey=thisMustBeExactly32CharactersLon
      - xpack.reporting.encryptionKey=thisMustBeExactly32CharactersLon
    depends_on:
      - elasticsearch
    networks:
      - elastic

volumes:
  esdata:

networks:
  elastic:
    driver: bridge